; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitc-02]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-c3-devkitc-02
monitor_speed = 115200
upload_speed = 115200
lib_deps =
	adafruit/Adafruit NeoPixel
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DFIRMWARE_VERSION=\"0.0.1\"
board_build.filesystem = spiffs
board_build.partitions = config/partitions_4mb_c3.csv
lib_ldf_mode = deep+
